name: Deploy to QA-fr

on:
  workflow_dispatch:  # This triggers when the release branch triggers it

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to QA-fr
      run: |
        echo "Deploying to QA-FR environment..."
        # Add your deployment commands here
        ls -la
