name: Handle Deployment

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Commit Message
      id: get-commit-message
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: Extract Label
      id: extract-label
      run: |
        LABEL_FROM_COMMIT=$(echo "${{ env.COMMIT_MESSAGE }}" | grep -o 'label=[^ ]*' | cut -d'=' -f2)
        echo "LABEL_FROM_COMMIT=$LABEL_FROM_COMMIT" >> $GITHUB_ENV

    - name: Read Deployment Label
      id: read-label
      run: |
        if [ -f deployment-config.txt ]; then
          LABEL=$(grep 'label=' deployment-config.txt | cut -d'=' -f2)
          echo "LABEL=$LABEL" >> $GITHUB_ENV
        else
          echo "deployment-config.txt not found."
          exit 1
        fi

    - name: Compare Labels and Trigger Workflows
      run: |
        if [ "${LABEL_FROM_COMMIT}" == "${LABEL}" ]; then
          echo "Labels match. Triggering workflows in qa and qa-fr branches..."

          # Trigger the qa workflow
          curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/qa.yml/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref":"qa"}'

          # Trigger the qa-fr workflow
          curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/qa-fr.yml/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref":"qa-fr"}'
        else
          echo "Labels do not match. No workflows will be triggered."
        fi
