name: Deploy Matching Commit Message Label PRs

on:
  push:
    branches:
      - release/*  # Triggers on any push to branches starting with 'release/'
      
jobs:
  trigger_qa_deployments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Read Deployment Label
      id: read-label
      run: |
        # Read the label from deployment-config.txt
        LABEL=$(grep 'label=' deployment-config.txt | cut -d'=' -f2)
        echo "Label found: $LABEL"
        echo "LABEL=$LABEL" >> $GITHUB_ENV

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Deploy PRs with Matching Commit Message Label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABEL: ${{ env.LABEL }}
      run: |
        # Fetch all open PRs
        PRS=$(gh pr list --state open --json number --jq '.[].number')

        # Initialize flag to track unapproved PRs
        ALL_APPROVED=true

        # Loop through each PR
        for PR in $PRS; do
          echo "Checking PR #$PR"

          # Fetch the commit messages for the PR and check for the LABEL in any of the commit messages
          MATCHING_COMMIT=$(gh pr view $PR --json commits --jq ".commits | map(select(.commit.message | contains(\"$LABEL\"))) | length")

          if [ "$MATCHING_COMMIT" -eq 0 ]; then
            echo "No matching commit message label found in PR #$PR. Skipping deployment."
            continue
          fi

          # Check if the PR is approved
          APPROVAL_COUNT=$(gh pr view $PR --json reviews --jq '.reviews | map(select(.state == "APPROVED")) | length')

          if [ "$APPROVAL_COUNT" -eq 0 ]; then
            echo "PR #$PR is not approved."
            ALL_APPROVED=false
          else:
            echo "PR #$PR has matching commit message label and is approved. Triggering downstream deployments..."

            # Trigger workflows in the qa and qa-fr branches
            gh workflow run deploy-qa.yml --ref qa
            gh workflow run deploy-qa-fr.yml --ref qa-fr
          fi
        done

        # Fail the workflow if any PRs were not approved
        if [ "$ALL_APPROVED" = false ]; then
          echo "Some PRs were not approved. Failing the workflow."
          exit 1
        fi
