name: List Directories on Branch Commit

on:
  push:
    branches:
      - qa
      - qa-fr
      - release/*  # Triggers on any push to branches starting with 'release/'

jobs:
  list_directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get the latest commit message
      id: get-commit-message
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Commit message: $COMMIT_MESSAGE"
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: Extract the label from commit message
      id: extract-label
      run: |
        # Extract the label from the commit message (assuming format: 'label=YOUR_LABEL')
        LABEL_FROM_COMMIT=$(echo "${{ env.COMMIT_MESSAGE }}" | grep -oP '(?<=label=)\d+')
        echo "Extracted label from commit message: $LABEL_FROM_COMMIT"
        echo "LABEL_FROM_COMMIT=$LABEL_FROM_COMMIT" >> $GITHUB_ENV

    - name: Read Deployment Label
      id: read-label
      run: |
        # Check if deployment-config.txt exists
        if [ -f deployment-config.txt ]; then
          # Read the label from deployment-config.txt
          LABEL=$(grep 'label=' deployment-config.txt | cut -d'=' -f2)
          echo "Label found: $LABEL"
          echo "LABEL=$LABEL" >> $GITHUB_ENV
        else
          echo "deployment-config.txt not found."
          exit 1
        fi

    - name: Compare Labels and List Directories
      run: |
        echo "Comparing labels..."
        echo "Commit Label: ${LABEL_FROM_COMMIT}"
        echo "Deployment Config Label: ${LABEL}"
        if [ "${LABEL_FROM_COMMIT}" == "${LABEL#sc-}" ]; then
          echo "Labels match. Listing all directories..."
          find . -type d
        else
          echo "Labels do not match. No directories will be listed."
        fi

    - name: Check if Trigger Needed for Other Branch
      if: ${{ github.ref == 'refs/heads/qa' }}
      run: |
        # Check for changes in `qa-fr` if currently on `qa` branch
        echo "Checking `qa-fr` branch for triggers..."
        git fetch origin qa-fr
        # Check if there are any new commits in `qa-fr`
        NEW_COMMITS=$(git log origin/qa-fr --not HEAD)
        if [ -n "$NEW_COMMITS" ]; then
          echo "There are new commits in `qa-fr`. Triggering workflow for `qa-fr`."
          # You could add a call to the GitHub API to trigger another workflow here if needed
        else
          echo "No new commits in `qa-fr`. No action needed."
        fi
